### ISSUE TITLE
Maintenance status?

### ISSUE THREAD

**Issue by fgblomqvist** [pablosichert/react-truncate#116]
Is this package still maintained? Seems like there are some decent PRs that would be useful to merge (e.g. https://github.com/One-com/react-truncate/pull/108).

If the package is looking for a maintainer it might be useful to put a note in the README at the top explaining the maintenance status (e.g. not actively maintained, looking for a maintainer, considered feature-complete etc.).

**Comment by VimLeSai** [comment]
Hie @gustavnikolaj , 
I see that this repo need to be maintained and i'm rookie here in this opensource world maybe you can guild me to help this around. And let's see what we can do better here.

Here to learn and help and keeping great repo like this alive in this opensource world. please ping me here or contact me on desai.vimal250@gmail.com .

**Looking forword to contribute and make opensource world better.**

**Comment by pablosichert** [comment]
Hey there,

I will take some time in the coming weeks to work on open issues.

I definitely won't add each and every feature, but maybe we can find a way to make the library more extensible for those who need to implement some specific behavior.
