### ISSUE TITLE
React v17 support

### ISSUE THREAD

**Issue by superpav** [pablosichert/react-truncate#139]
Are there any plans to support [React v17](https://reactjs.org/blog/2020/10/20/react-v17.html)?

**Comment by pablosichert** [comment]
Yes, that should be possible. Could you try it out with React 17 and report back if it gives any errors?

**Comment by superpav** [comment]
It seems to be working fine, I have tried to install it to a repo with React 17 and there were no runtime issues. I'll try to submit a PR in order to resolve peer dependency warning
